Novo provider Daemon  e exemplo para Lazarus.
HashLoad/horse pull request #147
Opened 2020-11-02 21:20 UTC by chacalfloripa

Foi implementado um novo provider e o exiemplo de como usar ele.

2020-11-04 02:26 UTC, viniciussanchez requested changes

2020-11-04 02:26 UTC, viniciussanchez commented on src/horse.provider.fpcdaemon.pas
> +    class property Running: Boolean read GetRunning;
Substituir para IsRunning igual os demais providers que possuem o recurso para manter o padrão

2020-11-18 20:21 UTC, viniciussanchez approved these changes

2020-11-18 21:37 UTC, CarlosHe approved these changes

2020-11-19 02:49 UTC, snakeice approved these changes

2020-11-19 11:40 UTC, viniciussanchez commented
@chacalfloripa antes de aceitar a PR, poderia me explicar o porque de ter criado a classe THTTPServerThread?
Pergunto porque no daemon do Delphi, não tivemos a necessidade...

2020-11-19 13:05 UTC, chacalfloripa commented
@viniciussanchez  isso foi necessário pois o TFPHTTPServer trava quando é ativado e colocando ele dentro da thread conseguimos continuar a inicialização do serviço.

2020-11-19 13:22 UTC, merged